name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */5 * * *" # Atualiza a cada 5 horas
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: LeonardoDuct
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit e push das mudanças
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualizando a animação da cobrinha"
          branch: output

      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

